### PR TITLE
Add third-party page with links to external nerves-related projects

### PR DESCRIPTION
**Pull request by arjan**

### CODE REVIEW

**Comment by arjan** [comment]
image

**Comment by fhunleth** [comment]
Thanks! This seems like a really good idea. I'll wait for comments from @mobileoverlord and @ghitchens in case there's a better location, but I think we should merge.

**Comment by arjan** [comment]
Cool :)

**Comment by mobileoverlord** [comment]
I like it. @ghitchens what do you think?

**Comment by arjan** [comment]
If you know any other external libraries please add them. I search github but couldn't find any others so far. Now that I think of it, it's worth mentioning elixir_ale on this page as well.

**Comment by fhunleth** [comment]
@arjan - We actually don't have a good place for listing nerves_uart and nerves_leds. Those would fall under the hw list too except that the page is titled "Third-party". How about renaming the tab to "Libraries" and tweaking the text?

I'm also having second thoughts about the Example projects section. I like the idea of having a list of example projects to look at, but I'm worried that given all of the changes at the moment with Nerves that the projects will go out of date or not show best practices. I think we should delete that section for now. If there is a feeling that it's not obvious where Nerves example applications are, then we can point them to the nerves-examples project. I'd like to encourage people to add simple examples to that, since at least for the near term, we can easily update it as we improve the tooling.

**Comment by ghitchens** [comment]
@arjan I agree with @fhunleth that the example projects is premature given the state of the framework and tooling right now.  IT's just premature.   IT's hard enough to keep nerves-examples up to date with current practices.

Regarding the libraries area, if we want to turn it into "libraries", I'd vote for a libraries page dedicated only to listing libraries, both "core" and "3rd party".   I do think it makes some sense to segment 3rd party libraries from "core" libraries, but the breakdown between hardware support and non-hardware support libraries is a bit tricky sometimes.   There are also thinks like nerves_firmware_http that are libraries but not hardware related that seem appropriate to list there.

**Comment by arjan** [comment]
Ok, I'll do the following:

- [ ] Change the page name to 'libraries' from 'third party'
- [ ] Separate into "core" (listing nerves_*) and "third party" (listing the current ones under "hardware")

Let's skip the (external) examples listing for now. We need to discuss where to put this (the news section also has an examples category but this is broken atm)

**Comment by GregMefford** [comment]
Thanks for working on this, Arjan! It's something we've been talking about
for a while but haven't taken that first step yet to make it happen. I'm
excited to have an official place to start collecting this list as things
come up.

**Comment by arjan** [comment]
Here you go: 

image

I added most core libraries, but only the "top level" ones, not the ones which are dependencies of others (e.g. wpa_supplicant).

**Comment by fhunleth** [comment]
Looks good. I agree with your decision to only list top level dependencies. 

Minor nits: 
  1. Can you change Nerves.IO.Neopixel and Nerves.IO.RC522 to their project names for consistency with the others?
  2. Also, could you change the hyperlinks to go to the hex.pm locations. Main reason: the hex.pm URLs are effectively permanent. Repo/home page changes won't result in our links getting invalidated.

**Comment by arjan** [comment]
[Already did](https://github.com/nerves-project/nerves-project.github.com/pull/23/commits/9986d9287c10d65b78deadf3f5c060279f930099#diff-409be6737e52741ae9f8c0f641d30da0R41) 1) but made the screenshot too soon :)

Will change the URLs.

**Comment by arjan** [comment]
Done; some packages aren't published on hex.pm yet.

**Comment by fhunleth** [comment]
Thanks! This looks great.

**Comment by arjan** [comment]
No problem, happy to help :)

**Pull request merged**
