### PR TITLE
Site cleanup, organization, and redesign

### PR DESCRIPTION
**Pull request by jerel**
Here is my work on an updated website. Included:

* [x] new header and site logo
* [x] responsive across desktop, tablet, mobile
* [x] search engine friendly page titles and markup
* [x] responsive video embeds on /watch
* [x] removed hardly-used /news
* [x] added embedded twitter feed since twitter is well used
* [ ] product photos or other snazzy design stuff

### CODE REVIEW

**Comment by fhunleth** [comment]
Sweet! I haven't gotten any product photos yet. I'll update when I do, but I suspect that I'll have to reach out to people directly. Most of what I know is internal use or early in product dev so no one wants to share yet.

I haven't looked at this yet, but is there a place for Nerves project sponsors? Le Tote, Rose Point Navigation Systems and my company, Troodon Software, all are contributing quite a bit to make Nerves real, so it would be nice to have room for their logos.

**Comment by jerel** [comment]
For my part product photos don't have to block merge if you end up liking the rest of the PR. Maybe we can get someone that's a better designer than I to add a product showcase a couple months down the road.

Ah right, sponsors. I could place them on the home page right below the hardware section. Or if it will only be several logos we could make a site wide footer with sponsor names/logos in it.

**Comment by fhunleth** [comment]
I give. I keep getting errors about unresolved specs when I try to run `jekyll` locally. Would you mind posting an image of the new website's front page.

**Comment by jerel** [comment]
I'll do one better. Here's a live staging site: https://nerves.jerel.co/

**Comment by fhunleth** [comment]
Looks good, and thank you so much for staging it for me!

I'm not sure if it's Firefox, but the header looks really tall to me. When I maximize Firefox, I can see the text down to "Nerves is young" which isn't that far down the page. The header takes up a little over half the space.

Also, on the "latest news", is it supposed to show the Twitter feed? It's not for me.

I think that for the "See all hardware", we'll need a page similar to the libraries one, since the GitHub repo doesn't make it obvious. This is one of those things where if you get me started with something, I can add the rest.

And one trivial one, on the "most popular prototyping boards", could you delete Intel Galileo? We thought that it would be popular give how many people requested it, but no one seems to use it.

**Comment by ghitchens** [comment]
@jerel Thanks again for moving this forward.   I'm sorry I haven't been more responsive, I am digging out from another month that has been unexpectedly challenging.   I've had a few of those this year.  

I do really like the top background, and I think the cleaned up content is good, I guess my main issue is how navigation and header play into the larger sign redesign.

For instance, while I think the visual impression is good upon first landing, the navigation doesn't jibe will with the tall graphic (being below the graphic rather than incorporated into or above it).  This means that all pages on the site generally will have the graphic above the menu, and take away from the vertical real estate.  I don't know if this was your long term intent, I imagine not. 

I do like the idea of moving toward a site design where that graphic is the landing, and for very tall one page sites it works well, like... http://www.elixirdaze.com.

For sites where there are multiple pages with navigation, I usually see the menu carried across the top of the page above the tall graphic, and sometimes a truncated version carried as theme for other pages, such as http://phoenixframework.org, or sometimes used as a background (as in http://quip.com).

Any chance you'd concur on the navigation issue?   




-

**Comment by GregMefford** [comment]
Sorry it took a while for me to respond as well - I've been slammed for the past week.

I really like the feel of your updated design, thanks for putting it together!
To make sure we're legally-covered, do you have rights to use the background image and fonts?
Did you create them yourself or get them under an appropriate license from somewhere?

I appreciate how much code you were able to trim out as well - that will hopefully help make things easier to maintain over time.

I agree with @fhunleth that the header image might be a bit too tall, particularly on low-resolution screens. I also agree with @ghitchens that it would be good to just have a "truncated" version of the navigation menu on the sub-pages, ideally still with the logo included, to save the vertical space.

**Comment by fhunleth** [comment]
I was told by @mobileoverlord that I had no design sense and big header images was what all of the cool people did nowadays. I hereby defer to the cool people for what they want.

**Comment by mobileoverlord** [comment]
😄 all the cool kids are doing big landing images. I like it. Makes me smile. Lets check on the truncated nav on subs and hopefully we can merge this and keep the momentum going. Thanks @jerel

**Comment by jerel** [comment]
Alright, I pushed some updates. You can view them at https://nerves.jerel.co

@fhunleth the Latest News definitely should show the twitter feed. It's twitter's own widget so I doubt it should be an error; perhaps you're running adblock, noscript, or similar that blocks it? For "See All Hardware" a text list like "Libraries" can currently be done by copying it but if you want a page that shows photos for the hardware or etc then something would need to be designed yet. I don't have any ideas at the moment.

@ghitchens / all: For the header I made some edits that should take everybody's feedback into consideration. Let me know what you think. I didn't remove the header completely on subpages with the reasoning that some visitors may come in from a Google search and not even hit the home page so it would be nice to have the look fairly similar. Happy to change yet if needed.

@GregMefford the header image started as [a public domain image](https://openclipart.org/detail/169900/circuit-board) and then I edited it from there. The logo is using Orbitron from Google Fonts.

**Comment by fhunleth** [comment]
@jerel This looks great. I do have an adblocker and it kills the Twitter feed. When I turn it off, everything looks as expected. While it sounds like there are a couple things that we may want to iterate on, your page is such an improvement that I'm going to merge it and we can add those things later.

**Comment by ghitchens** [comment]
@jerel I agree this is a major improvement, and thanks, @fhunleth for merging it.     I agree the big landing image is nice.   I also now like the menus near the top.    I personally think the shrunken header on some of the other pages would be better omitted in favor of the navbar.

**Comment by GregMefford** [comment]
@jerel: Thanks for all your work on this! I'm very happy with the improvement and I agree with @fhunleth that we can continue to iterate on the small things from here. 🚀 🌟

**Pull request merged**
