### PR TITLE
Current state documentation

### PR DESCRIPTION
**Pull request by timbuchwaldt**

### CODE REVIEW

**Comment by timbuchwaldt** [comment]
From my side this is complete with the stuff I came up with - if anyone has additions/thoughts - now is the time :)

**Comment by fhunleth** [comment]
I like the idea. I have a couple items that they'd tweak but it's minor. Since I haven't been maintaining the website, @GregMefford and @mobileoverlord what do you think? How does this fit in with the `bake` to `mix` round of documentation updates?

**Comment by mobileoverlord** [comment]
👍 @fhunleth we should probably change the wifi link?

**Comment by fhunleth** [comment]
Yes. I wanted to make sure that we're good with this from a high level first. It sounds like you and I are. 

Given that, I'm not sure about the high level categories. Instead of Level 1, 2, 3, how about "Embedded development", "Hardware integration", "Networking", "User interface". I separated out "Networking", since it has lots of parts. For the "User interface", I would put the "HTML Rendering" and "Video Playback" features. 

For wifi, the URL will be https://github.com/nerves-project/nerves_interim_wifi as soon as I get a chance to actually work on it.

Regarding GPIO, I'd make that GPIO/I2C/SPI so there's only one reference to Elixir/ALE.

For Persistent storage, I'd remove the "SD Card" part, since it could be eMMC. It would be nice to have a package that handles checking, fixing, mounting and unmounting the application data partition. I don't think that anyone has separated out the code that does that into a project. We may want to put it in the `nerves` project too.

For audio output, there's ALSA. The only platform that I've used it on is the EV3, though, and that was with `aplay` on the commandline. I don't know of an Elixir wrapper for ALSA, but that sure would be nice.

For the HTTP server, it would be nice to link a getting started doc for Phoenix on Nerves. @mobileoverlord, weren't you working on this or is this on your super long list of things to get done?

Then for "embedded development", I'd add build integration with `mix`. That was a huge effort. 

@timbuchwaldt: Thanks for starting this discussion. I think @mobileoverlord and I should take a pass at the details so if you have questions on those, don't worry about it, but could you address the high level organization?

**Comment by timbuchwaldt** [comment]
Thanks for the feedback, will try to incorporate that on my next commute :)

**Comment by timbuchwaldt** [comment]
So after a mishap with the commute I finally found time to restructure it based on the structure by @fhunleth

**Comment by GregMefford** [comment]
This looks good to me as an improvement, and we can iterate more on it over time.

Now that there's much more up-to-date docs on Hexdocs (https://hexdocs.pm/nerves/getting-started.html), I need to go through and figure out what still belongs on the Nerves website and maybe just link to Hexdocs for the rest.

**Comment by GregMefford** [comment]
I just wanted to make a note that I replaced the **Learn** page on the website with a link to the updated HexDocs, but I still think this table makes sense to put somewhere.

@mobileoverlord, do you think it makes sense to put this into the HexDocs as a "project status" page or something like that, or maybe a page on the website? I'm kind of leaning toward putting it on HexDocs because then it could be more easily tied to the version of the `nerves` package it refers to. It's a pretty minor thing, though, so I don't think it matters much either way.

**Comment by fhunleth** [comment]
This PR is feeling like a casualty of several of us getting inundated with NervesCamp and ElixirConf work, and I lost track of it. @timbuchwaldt - so sorry about that!

@mobileoverlord and @GregMefford: I like the idea of putting this content in the hex docs. Any concerns with doing that and closing this PR?

**Comment by GregMefford** [comment]
@fhunleth I agree that it should go on HexDocs, since the guides and FAQ are also there. I'm not exactly sure where to put it there, though.

Should it be at the top of the "Getting Started" page, to clearly set expectations for newcomers?
Should it perhaps be a new "Overview" page that describes what Nerves is and the current status of the project, separate from the details of how to get started?
Any other ideas?

**Comment by fhunleth** [comment]
I was thinking that it would be a standalone section at the end with a reference to it in the beginning. While it's good to set expectations, I don't think many users will be ready for this level of detail when they read the "Getting Started" page unless they're specifically browsing the docs for status.

**Comment by GregMefford** [comment]
Yeah, that makes sense to me!

**Comment by fhunleth** [comment]
Ok to close this? It seems like the information here ended up in other locations.

**Comment by GregMefford** [comment]
I agree that most of these items have become part of the standard docs and community tribal knowledge at this point, or included in the Libraries page. Sorry we never got this officially merged, but thanks for taking the time to document, and definitely let us know if you feel like the docs are still unclear on some of this stuff so we can fix it.

**Pull request closed without merging**
