### PR TITLE
added libraries from NAR

### PR DESCRIPTION
**Pull request by entone**

### CODE REVIEW

**Comment by fhunleth-lkc** [comment]
Could you publish to hex.pm? Except for a couple exceptions that need to be cleaned up, we decided that we only wanted hex.pm links listed here. Sorry if this wasn't clear.

**Comment by mobileoverlord** [comment]
Wow you guys have been busy, great contribution! Let me know if you need help getting those set up on Hex :bowtie: Thanks @entone

**Comment by entone** [comment]
I've still got a few things to clean up before I start versioning them, but
wanted to get them up for ElixirConf.

I'll get them on Hex soon!

**Comment by entone** [comment]
I'm going to update the documentation for my mDNS library and MOVI voice shield, and add those today as well.

**Comment by entone** [comment]
Ok, that's everything for now ;)

**Comment by fhunleth** [comment]
Merged! Thanks!

**Pull request merged**
