### PR TITLE
RFC: promo up

### PR DESCRIPTION
**Pull request by josevalim**
Hello @nerves-project!

A long time ago, Elixir had a home page quite similar to Nerves. We focused a lot on the implementation details and how things worked instead of focusing on what people can effectively build with it. For example, we said Elixir was a dynamic language with pattern matching and protocols. We eventually improved it based on external feedback.

Therefore the goal with this pull request is to apply the same feedback Elixir got in the past to Nerves. I.e. focus a bit more on what people can achieve with Nerves and, even more importantly, all the things they *do not need to do* because Nerves solves it for them.

Those are just ideas. There are probably innacuracies too so feel free to adapt or fully discard them (and I am not a native speaker!). Btw, it would also be great to include a link to the "rock-solid shipping industrial products".

Screenshot:

screen shot 2016-06-04 at 00 46 57

### CODE REVIEW

**Comment by fhunleth** [comment]
@josevalim, thanks for taking the time to edit this! I like these changes a lot. I have really minor nits which will be trivial for me to address when we merge.

@ghitchens, @mobileoverlord, @GregMefford - I know that there was talk of updating the website. Do we mess anything up if we merge this, and I make a couple minor updates? FWIW, my changes will be in the firmware size stats (we can get as low as 10 MB now, and I may get to make it smaller when we have Linkit Smart support. I'll update then.) and minor tweaks to a couple sentences, but the overall idea would stay the same.

**Comment by mobileoverlord** [comment]
I completely agree, these talking points focus more on the overview of what Nerves can get you to build and less about the details on how we do it. This is the proverbial "hitting the nail on the head" with what content should go on the site, and what content should go in guides / docs.

**Comment by ghitchens** [comment]
@josevalim Thanks for helping on this.   I agree with the spirit of your changes, especially to the descriptive paragraphs, which I like much better than the old ones.   I do think the tagline change needs discussion, I'm not happy with the new one yet, but I don't think the rest has to be held up for that.

@fhunleth I'm fine with merging this (sans tagline).  Here are a couple things maybe you could address when you make your changes:

- I  picked all lower case titles entirely for stylistic reasons.    I'm ok with dropping the lowercase titles in favor of Capitalization, but If we want to move away from all lower case titles then we need to move completely away, not mix them --the tagline should start with a capital, and Nerves should be capitalized in the Title as well then.    I'm OK either way (upper or lower), as long as we're consistent.

- A couple minor grammar things... The platform bullet needs "a 20MB image that starts" rather than just "a 20MB that starts".  Agree with @fhunleth that we shouldn't say 20mb.   It can be a lot smaller, it can be a lot bigger, depending on if we're bringing in wifi, gui, etc.   I'd vote for something like "a tiny image" rather than a number, or say "as small as 10mb" (or whatever number).  In the third bullet, "Our tools got you covered" is cute but given that the rest of the page dropped the quirky voice, I'd vote for "Our tools have you covered"d

So, given those things, I'm all for merging this in. 

Regarding the tagline, I'd prefer we hold off until we can discuss it further here, or on slack, or in person in a couple weeks.  

I think the tagline is very important, it's the first sentence someone reads about Nerves when trying to decide what it is, and sets the emotional impression for the rest of the page.  

The current tagline was intended to be active, edgy, and imply the characteristics of creatively and productivity building something that is extremely reliable.   The former tagline had all those components in it (Craft, Bulletproof, Stunningly Productive).  The proposed tag line doesn't have any of them.

If we're going to change the tagline (which I'm fine with), let's design it to convey the right image in one line.  Microsoft used to have this whole "information at your fingertips" tagline which used to bug me too, and was widely mocked inside and outside the company, so maybe I'm biased against the fingertip image.

Anyway, thanks again @josevalim for your good work on this - other than the tagline, I'm on board with it.

**Comment by fhunleth** [comment]
@ghitchens Thanks for the catch on the tagline. I'll defer pending further discussion.

Regarding the capitalization, I haven't consciously been paying attention, but thinking about it, I capitalize Nerves far more frequently than not. Looking at our GitHub repos and their docs, I'm not alone. I agree on your point on consistency. I'll update it here, and if you find other places let me know (or update it yourself). 

I'll make a pass tomorrow when I have a fresher head.

**Comment by GregMefford** [comment]
@josevalim: Thanks again for this. It's funny that I was just tonight thinking about how we could improve our first-impression, then I noticed this PR about it! I'm on board with the proposed changes.

@fhunleth: It won't break anything I've been working on, and it's definitely in the same direction I was intending to go, but just hadn't yet. I agree with the capitalization changes as well. I find that I normally capitalize some of our "key words" like Nerves, Platform, and Toolchain. We should work towards consistency across the docs and the website.

**Comment by josevalim** [comment]
I am glad you enjoyed the proposed changes! :D

> The current tagline was intended to be active, edgy, and imply the characteristics of creatively and productivity building something that is extremely reliable. The former tagline had all those components in it (Craft, Bulletproof, Stunningly Productive). The proposed tag line doesn't have any of them.

@ghitchens, I just want to add some rationale on the tagline change: the only word I wanted to remove was "firmware". :) That's because, from my understanding, the goal of nerves is not to "craft firmware". Firmwares are just a mechanism for crafting amazing embedded systems.

At his keynote, @mobileoverlord made a comparison of making building embedded systems as simple as Rails made building web applications 10 years ago. Rails initial tagline was "web development that doesn't hurt". The current tagline was meant to be similar in spirit. It was also a play on words (which I have no idea if it worked): you have the device at your fingertips both literally and programming-wise.

Anyway, that's the rationale, I am not attached to any of those changes. :D

Another idea to consider is to use those words "bulletproof", "stunning productive" as the headers in the description. For example:

* Platform: Bulletproof or Bulletproof platform
* Framework: Stunningly productive or Productive framework
* Tools: Crafting ???

We did this in Phoenix (but not in Elixir): http://www.phoenixframework.org/

PS: I pushed a small change that adds battle-hardened adjective to the Erlang VM in the first description.

**Comment by ghitchens** [comment]
@josevalim Thanks for the explanation of intent on the tagline.  I think I understand where you're coming from.  I concede that for the hobbyist market, "crafting firmware" is not ideal.    I think you did get to the crux of the matter when you compared with the Rails tagline.   It doesn't sound to me like  "Firmware development that doesn't hurt" would work for you either, although I like it :)

> from my understanding, the goal of nerves is not to "craft firmware". Firmwares are just a mechanism for crafting amazing embedded systems.

I think part of the disconnect for me was that from my perspective, as someone who builds and ships embedded systems commercially, crafting an amazing embedded system involves choosing (or designing) the right CPU board, designing I/O hardware, dealing with issues like electromagnetic compatibility and power supply choice (or design), finding the right case, connectors, or mounting arrangements, passing conformance and environmental testing, manufacturing and assembly and test considerations, burn-in and provisioning system, as well as building the right firmware.   Nerves can't help with much of that, just the firmware, and that's not a small thing.

Having said that, I think for someone who doesn't live in the world of building commercially, for the hobbyist / experimenter, "crafting embedded systems" brings to mind getting their Raspberry Pi to start doing something cool, where most of the concerns I have as a manufacturer don't come into play.   I agree with you that focusing on Embedded Systems and not Firmware makes sense for that crowd.

I can see myself liking "Embedded development that doesn't hurt", or "Embedded systems that just work", or "Bulletproof your embedded development with Elixir". 

> Another idea to consider is to use those words "bulletproof", "stunning productive" as the headers in the description.

I like this idea a lot.

My personal reaction to "keep...at your fingertips", is from someone who lived through Microsoft in the 90's and got so tired of hearing the "Information at your fingertips" company vision repeated at every company meeting, meanwhile having a butchered Internet strategy and ignoring the search search engine business.  .....Anyway....

Justin, Frank, and I are all getting together in less than 2 weeks to hash out some things, so hopefully we'll come up some with good ideas then as well.

I want to be clear:  I *truly* appreciate your interest and help in getting our Nerves messaging right and the support your'e giving Nerves.  All of us absolutely appreciate all your help and ideas!

**Comment by josevalim** [comment]
> I think part of the disconnect for me was that from my perspective, as someone who builds and ships embedded systems commercially

Yes, I agree I see it only from the hobbyist perspective and you just did a great job explaining why it is much more nuanced than that!

> I can see myself liking "Embedded development that doesn't hurt", or "Embedded systems that just work", or "Bulletproof your embedded development with Elixir".

"Bulletproof your embedded development" feels incomplete because my impression is that Nerves does much more than bulletproofing! It seems Nerves is also becoming one of the simplest and fastest ways of developing and deploying embedded software. I am not sure how much this impression applies to custom embedded hardware but I think that's a perspective that may be worth taking into account too. Again, I am just spitballing, but here are other suggestions to consider:

* Craft and deploy bulletproof embedded software with Elixir
* The simplest/fastest/easiest way to craft and deploy bulletproof embedded software (if you are feeling ambitious)
* The simplest/fastest/easiest way to build and deploy robust embedded software (as above but using more "straight-forward" words)

> I want to be clear: I truly appreciate your interest and help in getting our Nerves messaging right and the support your'e giving Nerves. All of us absolutely appreciate all your help and ideas!

I am glad to help! But, as I said, don't take my suggestions here too seriously, my perspective on this is very limited. I just wanted to start the discussion (and it seems it worked). :)

**Comment by fhunleth** [comment]
FYI - In case anyone is looking at this branch and is seeing the conflicts, don't worry - no need to rebase. To my knowledge, the outstanding items for discussion are the tagline update and expansion of the website to include commercial users of Nerves. Everything else has been incorporated. The plan of record is to resolve the remaining items next weekend when we meet in DC.

**Comment by ghitchens** [comment]
@josevalim Frank, Justin and I all met this weekend in DC to hash out a bunch of stuff regarding Nerves, including the best tagline.   We went with a minor variant of your last suggestion!   Thanks again for all your help and support.

**Comment by josevalim** [comment]
@ghitchens glad to help! :D 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
